name: Deploy to Heroku Frontend

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: cd ./front && npm install
      - run: cd ./front && npm run build
      - name: Deploy to Heroku Frontend
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_FRONT}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "front"
